# Generated by Django 6.0.7 on 2026-07-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
