# Generated by Django 6.0.7 on 2026-07-21 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_alter_predictionresult_image_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finished_ai', 'Finished - AI Generated'), ('finished_real', 'Finished - Real'), ('failed', 'Failed')], max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='classifier.predictionresult')),
            ],
        ),
    ]
