# Generated by Django 6.0.7 on 2026-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_resultstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
